name: flutter_ui_splash_screen
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^4.0.2
  flutter_map: 
  flutter_youtube: "^1.1.4"   

    

flutter:
  uses-material-design: true
  
  assets:
    - images/sibat.png
    - images/wave.jpg
    - images/siklusbencana.jpg