name: flutter_ui_splash_screen
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^4.0.2
  flutter_map: 
  # flutter_youtube: "^1.1.4"   
  flutube: ^0.7.3
  # flutter_uxcam: ^1.0.0
  gradient_widgets: ^0.4.0
  tweet_webview: ^0.2.1
  flutter_launcher_icons: "^0.7.0"


    

flutter:
  uses-material-design: true
  
  assets:
    - images/sibat.png
    - images/siklusbencana.jpg
    - images/iconPmi.png
    - images/iconDamkarGunungKidul.png
    - images/iconBPBDGunungKidul.png
    - images/iconSarGunungKidul.png
    - images/iconPemerintahGunungKidul.png


flutter_icons:
  android: true 
  ios: true
  image_path_android: "images/sibat.png"
  image_path_ios: "images/sibat.png"