name: flutter_ui_splash_screen
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_map: 

flutter:
  uses-material-design: true

  assets:
    - images/sibat.png